### ISSUE TITLE
[Feature request] Add parameters from burp history

### ISSUE THREAD

**Issue by iamRjarpan** [xnl-h4ck3r/burp-extensions#1]
Hy can you add a feature to add all parameters from proxy history, So after understanding target I start this externsion and I click on "get all params" and it comes. Like paramalyzer but they has no feature to copy all those parameters

**Comment by xnl-h4ck3r** [comment]
Hey. Thanks for taking the time to suggest a new feature. If you have no scope set, then the site map will contain all of proxy history anyway. You can select everything in the site mpa and run GAP against it. However, generally I'm not sure you'd want to have all the paramaters from third party sites that aren't relevant to your target. 
There is also a very big update to this tool coming soon.
