### ISSUE TITLE
Could not import modules

### ISSUE THREAD

**Issue by mzhrisec** [xnl-h4ck3r/burp-extensions#10]
Hi 
Thank you for the great extension.
When i install new version 2.2 i got this errors `WARNING: Could not import beautifulsoup4 for word mode: No module named bs4` & `10 WARNING: Could not import html5lib for more accurate parsing of words by beatifulsc`
But extension works well.

<img width="1011" alt="Screenshot 2023-02-22 at 1 59 31 AM" src="https://user-images.githubusercontent.com/36299062/220474279-8ed97b29-c544-4d25-b3f2-56cae9163ab5.png">

**Comment by fleazy** [comment]
I am getting the same error here, tried updating pip, manual install of bs4 in the directory. No dice so far.

**Comment by fleazy** [comment]
I had the same error. It was fixed by [upgrading](https://www.jython.org/download) to jython 2.7.3 from 2.7.2 and following the install instructions from there.

**Comment by xnl-h4ck3r** [comment]
Hi @mzhrisec. Make sure you follow the instructions on the github README and you should be fine. If not though, let me know. Thanks
